### ISSUE TITLE
Editor crashes when opening a level

### ISSUE THREAD

**Issue by LB-KonradJuszczak** [o3de/ROSConDemo#210] opened 2022-12-09 14:09 UTC
**Describe the bug**
While opening newly created or already existing level in O3DE Editor, the engine crashes with a prompt in terminal: Segmentation fault (core dumped).

Note that project was setup by following the instruction: https://github.com/o3de/ROSConDemo/tree/main/docker

Please refer to the Editor.log provided as an attached file. Also please look at the hardinfo report from both PCs on which the problem occurs.
- [Hardinfo.zip](https://github.com/o3de/ROSConDemo/files/10195496/Hardinfo.zip)
- [Editor.log](https://github.com/o3de/ROSConDemo/files/10195456/Editor.log)

Please note that the issue occurs on 2 out of 4 machines and should be considered a critical.

**Steps to reproduce**
1. Launch the Editor.
2. Attempt to open any level.

**Expected behavior**
It is possible to open any level without problems.

**Actual behavior**
Editor crashes when opening a level.

**Found in Branch**
ROSConDemo: main ([eb54128](https://github.com/o3de/ROSConDemo/commit/eb541287f59a3bd345d8149688325eef43d8cdfd))
O3DE: Development ([43ecf18](https://github.com/o3de/o3de/commit/43ecf18cd1297703fb540e0df5f8d880b68e5541))

**Desktop**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.5 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPERS
- Memory: 16 GB

**Comment by LB-KonradJuszczak** [comment] 2022-12-12 14:39
Updated the Found in Branch with O3DE commit at the time of reporting:
ROSConDemo: main ([eb54128](https://github.com/o3de/ROSConDemo/commit/eb541287f59a3bd345d8149688325eef43d8cdfd))
O3DE: Development ([43ecf18](https://github.com/o3de/o3de/commit/43ecf18cd1297703fb540e0df5f8d880b68e5541))

**Comment by lumberyard-employee-dm** [comment] 2022-12-12 20:24
This issue might be related to an issue with the Editor crashing before the AssetProcessor processing all the critical assets: https://github.com/o3de/o3de/commit/17213adaaa1febeafafe8e351dcdd4dc7d336ee8

**Comment by forhalle** [comment] 2023-01-09 22:15
@spham-amzn will verify this issue and close if it can't be reproduced. @smurly was unable to reproduce on his machine using a subsequent commit.

**Comment by hultonha** [comment] 2023-01-31 10:35
@smurly Is this something that can be reviewed and closed as it seems to no longer be occurring. The development branch should be used.

**Comment by adamdbrw** [comment] 2023-02-10 09:55
@spham-amzn any luck reproducing this one?

**Comment by LB-TomaszSerwanski** [comment] 2023-02-10 13:38
Just a quick update - we have verified that this is no longer reproducible on our side (on the same machine on which it was originally reported) after upgrading to Ubuntu 22.04. Please note that closing the issue on our side is not possible due to lack of permissions in the ROSConDemo repository.

**Comment by adamdbrw** [comment] 2023-02-10 13:41
Thank you for verifying  @LB-TomaszSerwanski!

**Closed by adamdbrw** 2023-02-10 13:41 UTC
Labels: bug, priority/high
